version: "3.8"

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase_password
      - MB_DB_HOST=postgres
      - JAVA_OPTS=-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - JAVA_TIMEZONE=UTC
    volumes:
      - ./data:/metabase-data
    depends_on:
      - postgres
    networks:
      - metabase-network

  postgres:
    image: postgres:15
    container_name: metabase-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metabase-network

volumes:
  postgres_data:

networks:
  metabase-network:
    driver: bridge
